//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 15/7/2021 4:48:59 pm
namespace DomainModel.Entities
{
        /// <summary>
        /// There are no comments for VehicleMakeSingle in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("VehicleMakeSingle")]
    public partial class VehicleMakeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<VehicleMake>
    {
        /// <summary>
        /// Initialize a new VehicleMakeSingle object.
        /// </summary>
        public VehicleMakeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VehicleMakeSingle object.
        /// </summary>
        public VehicleMakeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VehicleMakeSingle object.
        /// </summary>
        public VehicleMakeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<VehicleMake> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for MotorVehicleModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModels")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicleModel> MotorVehicleModels
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._MotorVehicleModels == null))
                {
                    this._MotorVehicleModels = Context.CreateQuery<global::DomainModel.Entities.MotorVehicleModel>(GetPath("MotorVehicleModels"));
                }
                return this._MotorVehicleModels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicleModel> _MotorVehicleModels;
    }
        /// <summary>
        /// There are no comments for VehicleMake in the schema.
        /// </summary>
    /// <KeyProperties>
    /// VehicleMakeId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("VehicleMakeId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("VehicleMake")]
    public partial class VehicleMake : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VehicleMake object.
        /// </summary>
        /// <param name="vehicleMakeId">Initial value of VehicleMakeId.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static VehicleMake CreateVehicleMake(global::System.Guid vehicleMakeId, string name)
        {
            VehicleMake vehicleMake = new VehicleMake();
            vehicleMake.VehicleMakeId = vehicleMakeId;
            vehicleMake.Name = name;
            return vehicleMake;
        }
        /// <summary>
        /// There are no comments for Property VehicleMakeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VehicleMakeId")]
        public virtual global::System.Guid VehicleMakeId
        {
            get
            {
                return this._VehicleMakeId;
            }
            set
            {
                this.OnVehicleMakeIdChanging(value);
                this._VehicleMakeId = value;
                this.OnVehicleMakeIdChanged();
                this.OnPropertyChanged("VehicleMakeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _VehicleMakeId;
        partial void OnVehicleMakeIdChanging(global::System.Guid value);
        partial void OnVehicleMakeIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MotorVehicleModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModels")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicleModel> MotorVehicleModels
        {
            get
            {
                return this._MotorVehicleModels;
            }
            set
            {
                this.OnMotorVehicleModelsChanging(value);
                this._MotorVehicleModels = value;
                this.OnMotorVehicleModelsChanged();
                this.OnPropertyChanged("MotorVehicleModels");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicleModel> _MotorVehicleModels = new global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicleModel>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnMotorVehicleModelsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicleModel> value);
        partial void OnMotorVehicleModelsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
        /// <summary>
        /// There are no comments for MotorVehicleModelSingle in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModelSingle")]
    public partial class MotorVehicleModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<MotorVehicleModel>
    {
        /// <summary>
        /// Initialize a new MotorVehicleModelSingle object.
        /// </summary>
        public MotorVehicleModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MotorVehicleModelSingle object.
        /// </summary>
        public MotorVehicleModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MotorVehicleModelSingle object.
        /// </summary>
        public MotorVehicleModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<MotorVehicleModel> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for VehicleMake in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VehicleMake")]
        public virtual global::DomainModel.Entities.VehicleMakeSingle VehicleMake
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._VehicleMake == null))
                {
                    this._VehicleMake = new global::DomainModel.Entities.VehicleMakeSingle(this.Context, GetPath("VehicleMake"));
                }
                return this._VehicleMake;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DomainModel.Entities.VehicleMakeSingle _VehicleMake;
        /// <summary>
        /// There are no comments for MotorVehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicles")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicle> MotorVehicles
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._MotorVehicles == null))
                {
                    this._MotorVehicles = Context.CreateQuery<global::DomainModel.Entities.MotorVehicle>(GetPath("MotorVehicles"));
                }
                return this._MotorVehicles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicle> _MotorVehicles;
    }
        /// <summary>
        /// There are no comments for MotorVehicleModel in the schema.
        /// </summary>
    /// <KeyProperties>
    /// MotorVehicleModelId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("MotorVehicleModelId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModel")]
    public partial class MotorVehicleModel : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MotorVehicleModel object.
        /// </summary>
        /// <param name="motorVehicleModelId">Initial value of MotorVehicleModelId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="motorVehicleType">Initial value of MotorVehicleType.</param>
        /// <param name="fuelCapacity">Initial value of FuelCapacity.</param>
        /// <param name="fuelConsumption">Initial value of FuelConsumption.</param>
        /// <param name="engineType">Initial value of EngineType.</param>
        /// <param name="maxPower">Initial value of MaxPower.</param>
        /// <param name="transmissionType">Initial value of TransmissionType.</param>
        /// <param name="aWD">Initial value of AWD.</param>
        /// <param name="cargoVolume">Initial value of CargoVolume.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static MotorVehicleModel CreateMotorVehicleModel(global::System.Guid motorVehicleModelId, 
                    string name, 
                    global::DomainModel.Entities.MotorVehicleType motorVehicleType, 
                    double fuelCapacity, 
                    double fuelConsumption, 
                    global::DomainModel.Entities.EngineType engineType, 
                    int maxPower, 
                    global::DomainModel.Entities.TransmissionType transmissionType, 
                    bool aWD, 
                    int cargoVolume)
        {
            MotorVehicleModel motorVehicleModel = new MotorVehicleModel();
            motorVehicleModel.MotorVehicleModelId = motorVehicleModelId;
            motorVehicleModel.Name = name;
            motorVehicleModel.MotorVehicleType = motorVehicleType;
            motorVehicleModel.FuelCapacity = fuelCapacity;
            motorVehicleModel.FuelConsumption = fuelConsumption;
            motorVehicleModel.EngineType = engineType;
            motorVehicleModel.MaxPower = maxPower;
            motorVehicleModel.TransmissionType = transmissionType;
            motorVehicleModel.AWD = aWD;
            motorVehicleModel.CargoVolume = cargoVolume;
            return motorVehicleModel;
        }
        /// <summary>
        /// There are no comments for Property MotorVehicleModelId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModelId")]
        public virtual global::System.Guid MotorVehicleModelId
        {
            get
            {
                return this._MotorVehicleModelId;
            }
            set
            {
                this.OnMotorVehicleModelIdChanging(value);
                this._MotorVehicleModelId = value;
                this.OnMotorVehicleModelIdChanged();
                this.OnPropertyChanged("MotorVehicleModelId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _MotorVehicleModelId;
        partial void OnMotorVehicleModelIdChanging(global::System.Guid value);
        partial void OnMotorVehicleModelIdChanged();
        /// <summary>
        /// There are no comments for Property VehicleMakeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VehicleMakeId")]
        public virtual global::System.Nullable<global::System.Guid> VehicleMakeId
        {
            get
            {
                return this._VehicleMakeId;
            }
            set
            {
                this.OnVehicleMakeIdChanging(value);
                this._VehicleMakeId = value;
                this.OnVehicleMakeIdChanged();
                this.OnPropertyChanged("VehicleMakeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _VehicleMakeId;
        partial void OnVehicleMakeIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnVehicleMakeIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MotorVehicleType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleType")]
        public virtual global::DomainModel.Entities.MotorVehicleType MotorVehicleType
        {
            get
            {
                return this._MotorVehicleType;
            }
            set
            {
                this.OnMotorVehicleTypeChanging(value);
                this._MotorVehicleType = value;
                this.OnMotorVehicleTypeChanged();
                this.OnPropertyChanged("MotorVehicleType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DomainModel.Entities.MotorVehicleType _MotorVehicleType;
        partial void OnMotorVehicleTypeChanging(global::DomainModel.Entities.MotorVehicleType value);
        partial void OnMotorVehicleTypeChanged();
        /// <summary>
        /// There are no comments for Property FuelCapacity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FuelCapacity")]
        public virtual double FuelCapacity
        {
            get
            {
                return this._FuelCapacity;
            }
            set
            {
                this.OnFuelCapacityChanging(value);
                this._FuelCapacity = value;
                this.OnFuelCapacityChanged();
                this.OnPropertyChanged("FuelCapacity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _FuelCapacity;
        partial void OnFuelCapacityChanging(double value);
        partial void OnFuelCapacityChanged();
        /// <summary>
        /// There are no comments for Property FuelConsumption in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FuelConsumption")]
        public virtual double FuelConsumption
        {
            get
            {
                return this._FuelConsumption;
            }
            set
            {
                this.OnFuelConsumptionChanging(value);
                this._FuelConsumption = value;
                this.OnFuelConsumptionChanged();
                this.OnPropertyChanged("FuelConsumption");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _FuelConsumption;
        partial void OnFuelConsumptionChanging(double value);
        partial void OnFuelConsumptionChanged();
        /// <summary>
        /// There are no comments for Property EngineType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EngineType")]
        public virtual global::DomainModel.Entities.EngineType EngineType
        {
            get
            {
                return this._EngineType;
            }
            set
            {
                this.OnEngineTypeChanging(value);
                this._EngineType = value;
                this.OnEngineTypeChanged();
                this.OnPropertyChanged("EngineType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DomainModel.Entities.EngineType _EngineType;
        partial void OnEngineTypeChanging(global::DomainModel.Entities.EngineType value);
        partial void OnEngineTypeChanged();
        /// <summary>
        /// There are no comments for Property MaxPower in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MaxPower")]
        public virtual int MaxPower
        {
            get
            {
                return this._MaxPower;
            }
            set
            {
                this.OnMaxPowerChanging(value);
                this._MaxPower = value;
                this.OnMaxPowerChanged();
                this.OnPropertyChanged("MaxPower");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _MaxPower;
        partial void OnMaxPowerChanging(int value);
        partial void OnMaxPowerChanged();
        /// <summary>
        /// There are no comments for Property TransmissionType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TransmissionType")]
        public virtual global::DomainModel.Entities.TransmissionType TransmissionType
        {
            get
            {
                return this._TransmissionType;
            }
            set
            {
                this.OnTransmissionTypeChanging(value);
                this._TransmissionType = value;
                this.OnTransmissionTypeChanged();
                this.OnPropertyChanged("TransmissionType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DomainModel.Entities.TransmissionType _TransmissionType;
        partial void OnTransmissionTypeChanging(global::DomainModel.Entities.TransmissionType value);
        partial void OnTransmissionTypeChanged();
        /// <summary>
        /// There are no comments for Property AWD in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AWD")]
        public virtual bool AWD
        {
            get
            {
                return this._AWD;
            }
            set
            {
                this.OnAWDChanging(value);
                this._AWD = value;
                this.OnAWDChanged();
                this.OnPropertyChanged("AWD");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _AWD;
        partial void OnAWDChanging(bool value);
        partial void OnAWDChanged();
        /// <summary>
        /// There are no comments for Property CargoVolume in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CargoVolume")]
        public virtual int CargoVolume
        {
            get
            {
                return this._CargoVolume;
            }
            set
            {
                this.OnCargoVolumeChanging(value);
                this._CargoVolume = value;
                this.OnCargoVolumeChanged();
                this.OnPropertyChanged("CargoVolume");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _CargoVolume;
        partial void OnCargoVolumeChanging(int value);
        partial void OnCargoVolumeChanged();
        /// <summary>
        /// There are no comments for Property VehicleMake in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VehicleMake")]
        public virtual global::DomainModel.Entities.VehicleMake VehicleMake
        {
            get
            {
                return this._VehicleMake;
            }
            set
            {
                this.OnVehicleMakeChanging(value);
                this._VehicleMake = value;
                this.OnVehicleMakeChanged();
                this.OnPropertyChanged("VehicleMake");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DomainModel.Entities.VehicleMake _VehicleMake;
        partial void OnVehicleMakeChanging(global::DomainModel.Entities.VehicleMake value);
        partial void OnVehicleMakeChanged();
        /// <summary>
        /// There are no comments for Property MotorVehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicles")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicle> MotorVehicles
        {
            get
            {
                return this._MotorVehicles;
            }
            set
            {
                this.OnMotorVehiclesChanging(value);
                this._MotorVehicles = value;
                this.OnMotorVehiclesChanged();
                this.OnPropertyChanged("MotorVehicles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicle> _MotorVehicles = new global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicle>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnMotorVehiclesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::DomainModel.Entities.MotorVehicle> value);
        partial void OnMotorVehiclesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
        /// <summary>
        /// There are no comments for MotorVehicleSingle in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleSingle")]
    public partial class MotorVehicleSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<MotorVehicle>
    {
        /// <summary>
        /// Initialize a new MotorVehicleSingle object.
        /// </summary>
        public MotorVehicleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MotorVehicleSingle object.
        /// </summary>
        public MotorVehicleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MotorVehicleSingle object.
        /// </summary>
        public MotorVehicleSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<MotorVehicle> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for MotorVehicleModel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModel")]
        public virtual global::DomainModel.Entities.MotorVehicleModelSingle MotorVehicleModel
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._MotorVehicleModel == null))
                {
                    this._MotorVehicleModel = new global::DomainModel.Entities.MotorVehicleModelSingle(this.Context, GetPath("MotorVehicleModel"));
                }
                return this._MotorVehicleModel;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DomainModel.Entities.MotorVehicleModelSingle _MotorVehicleModel;
    }
        /// <summary>
        /// There are no comments for MotorVehicle in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicle")]
    public partial class MotorVehicle : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MotorVehicle object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="year">Initial value of Year.</param>
        /// <param name="vIN">Initial value of VIN.</param>
        /// <param name="mileage">Initial value of Mileage.</param>
        /// <param name="hasNavSystem">Initial value of HasNavSystem.</param>
        /// <param name="hasDashCam">Initial value of HasDashCam.</param>
        /// <param name="hasReversingCam">Initial value of HasReversingCam.</param>
        /// <param name="hasForwardParkingSensor">Initial value of HasForwardParkingSensor.</param>
        /// <param name="hasRearParkingSensor">Initial value of HasRearParkingSensor.</param>
        /// <param name="hasBlindspotMonitoring">Initial value of HasBlindspotMonitoring.</param>
        /// <param name="hasAutomaticEmergencyBrake">Initial value of HasAutomaticEmergencyBrake.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static MotorVehicle CreateMotorVehicle(global::System.Guid ID, 
                    int year, 
                    string vIN, 
                    int mileage, 
                    bool hasNavSystem, 
                    bool hasDashCam, 
                    bool hasReversingCam, 
                    bool hasForwardParkingSensor, 
                    bool hasRearParkingSensor, 
                    bool hasBlindspotMonitoring, 
                    bool hasAutomaticEmergencyBrake)
        {
            MotorVehicle motorVehicle = new MotorVehicle();
            motorVehicle.Id = ID;
            motorVehicle.Year = year;
            motorVehicle.VIN = vIN;
            motorVehicle.Mileage = mileage;
            motorVehicle.HasNavSystem = hasNavSystem;
            motorVehicle.HasDashCam = hasDashCam;
            motorVehicle.HasReversingCam = hasReversingCam;
            motorVehicle.HasForwardParkingSensor = hasForwardParkingSensor;
            motorVehicle.HasRearParkingSensor = hasRearParkingSensor;
            motorVehicle.HasBlindspotMonitoring = hasBlindspotMonitoring;
            motorVehicle.HasAutomaticEmergencyBrake = hasAutomaticEmergencyBrake;
            return motorVehicle;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public virtual global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MotorVehicleModelId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModelId")]
        public virtual global::System.Nullable<global::System.Guid> MotorVehicleModelId
        {
            get
            {
                return this._MotorVehicleModelId;
            }
            set
            {
                this.OnMotorVehicleModelIdChanging(value);
                this._MotorVehicleModelId = value;
                this.OnMotorVehicleModelIdChanged();
                this.OnPropertyChanged("MotorVehicleModelId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _MotorVehicleModelId;
        partial void OnMotorVehicleModelIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMotorVehicleModelIdChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Year")]
        public virtual int Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
                this.OnPropertyChanged("Year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Year;
        partial void OnYearChanging(int value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property VIN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VIN")]
        public virtual string VIN
        {
            get
            {
                return this._VIN;
            }
            set
            {
                this.OnVINChanging(value);
                this._VIN = value;
                this.OnVINChanged();
                this.OnPropertyChanged("VIN");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _VIN;
        partial void OnVINChanging(string value);
        partial void OnVINChanged();
        /// <summary>
        /// There are no comments for Property Registration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Registration")]
        public virtual string Registration
        {
            get
            {
                return this._Registration;
            }
            set
            {
                this.OnRegistrationChanging(value);
                this._Registration = value;
                this.OnRegistrationChanged();
                this.OnPropertyChanged("Registration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Registration;
        partial void OnRegistrationChanging(string value);
        partial void OnRegistrationChanged();
        /// <summary>
        /// There are no comments for Property Mileage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Mileage")]
        public virtual int Mileage
        {
            get
            {
                return this._Mileage;
            }
            set
            {
                this.OnMileageChanging(value);
                this._Mileage = value;
                this.OnMileageChanged();
                this.OnPropertyChanged("Mileage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Mileage;
        partial void OnMileageChanging(int value);
        partial void OnMileageChanged();
        /// <summary>
        /// There are no comments for Property HasNavSystem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasNavSystem")]
        public virtual bool HasNavSystem
        {
            get
            {
                return this._HasNavSystem;
            }
            set
            {
                this.OnHasNavSystemChanging(value);
                this._HasNavSystem = value;
                this.OnHasNavSystemChanged();
                this.OnPropertyChanged("HasNavSystem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _HasNavSystem;
        partial void OnHasNavSystemChanging(bool value);
        partial void OnHasNavSystemChanged();
        /// <summary>
        /// There are no comments for Property HasDashCam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasDashCam")]
        public virtual bool HasDashCam
        {
            get
            {
                return this._HasDashCam;
            }
            set
            {
                this.OnHasDashCamChanging(value);
                this._HasDashCam = value;
                this.OnHasDashCamChanged();
                this.OnPropertyChanged("HasDashCam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _HasDashCam;
        partial void OnHasDashCamChanging(bool value);
        partial void OnHasDashCamChanged();
        /// <summary>
        /// There are no comments for Property HasReversingCam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasReversingCam")]
        public virtual bool HasReversingCam
        {
            get
            {
                return this._HasReversingCam;
            }
            set
            {
                this.OnHasReversingCamChanging(value);
                this._HasReversingCam = value;
                this.OnHasReversingCamChanged();
                this.OnPropertyChanged("HasReversingCam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _HasReversingCam;
        partial void OnHasReversingCamChanging(bool value);
        partial void OnHasReversingCamChanged();
        /// <summary>
        /// There are no comments for Property HasForwardParkingSensor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasForwardParkingSensor")]
        public virtual bool HasForwardParkingSensor
        {
            get
            {
                return this._HasForwardParkingSensor;
            }
            set
            {
                this.OnHasForwardParkingSensorChanging(value);
                this._HasForwardParkingSensor = value;
                this.OnHasForwardParkingSensorChanged();
                this.OnPropertyChanged("HasForwardParkingSensor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _HasForwardParkingSensor;
        partial void OnHasForwardParkingSensorChanging(bool value);
        partial void OnHasForwardParkingSensorChanged();
        /// <summary>
        /// There are no comments for Property HasRearParkingSensor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasRearParkingSensor")]
        public virtual bool HasRearParkingSensor
        {
            get
            {
                return this._HasRearParkingSensor;
            }
            set
            {
                this.OnHasRearParkingSensorChanging(value);
                this._HasRearParkingSensor = value;
                this.OnHasRearParkingSensorChanged();
                this.OnPropertyChanged("HasRearParkingSensor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _HasRearParkingSensor;
        partial void OnHasRearParkingSensorChanging(bool value);
        partial void OnHasRearParkingSensorChanged();
        /// <summary>
        /// There are no comments for Property HasBlindspotMonitoring in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasBlindspotMonitoring")]
        public virtual bool HasBlindspotMonitoring
        {
            get
            {
                return this._HasBlindspotMonitoring;
            }
            set
            {
                this.OnHasBlindspotMonitoringChanging(value);
                this._HasBlindspotMonitoring = value;
                this.OnHasBlindspotMonitoringChanged();
                this.OnPropertyChanged("HasBlindspotMonitoring");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _HasBlindspotMonitoring;
        partial void OnHasBlindspotMonitoringChanging(bool value);
        partial void OnHasBlindspotMonitoringChanged();
        /// <summary>
        /// There are no comments for Property HasAutomaticEmergencyBrake in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasAutomaticEmergencyBrake")]
        public virtual bool HasAutomaticEmergencyBrake
        {
            get
            {
                return this._HasAutomaticEmergencyBrake;
            }
            set
            {
                this.OnHasAutomaticEmergencyBrakeChanging(value);
                this._HasAutomaticEmergencyBrake = value;
                this.OnHasAutomaticEmergencyBrakeChanged();
                this.OnPropertyChanged("HasAutomaticEmergencyBrake");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _HasAutomaticEmergencyBrake;
        partial void OnHasAutomaticEmergencyBrakeChanging(bool value);
        partial void OnHasAutomaticEmergencyBrakeChanged();
        /// <summary>
        /// There are no comments for Property LocationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationId")]
        public virtual global::System.Nullable<global::System.Guid> LocationId
        {
            get
            {
                return this._LocationId;
            }
            set
            {
                this.OnLocationIdChanging(value);
                this._LocationId = value;
                this.OnLocationIdChanged();
                this.OnPropertyChanged("LocationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _LocationId;
        partial void OnLocationIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnLocationIdChanged();
        /// <summary>
        /// There are no comments for Property MotorVehicleModel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModel")]
        public virtual global::DomainModel.Entities.MotorVehicleModel MotorVehicleModel
        {
            get
            {
                return this._MotorVehicleModel;
            }
            set
            {
                this.OnMotorVehicleModelChanging(value);
                this._MotorVehicleModel = value;
                this.OnMotorVehicleModelChanged();
                this.OnPropertyChanged("MotorVehicleModel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DomainModel.Entities.MotorVehicleModel _MotorVehicleModel;
        partial void OnMotorVehicleModelChanging(global::DomainModel.Entities.MotorVehicleModel value);
        partial void OnMotorVehicleModelChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
        /// <summary>
        /// There are no comments for MotorVehicleType in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleType")]
    public enum MotorVehicleType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Scooter")]
        Scooter = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Motorcycle")]
        Motorcycle = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("HatchBack")]
        HatchBack = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Sedan")]
        Sedan = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Wagon")]
        Wagon = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompactSUV")]
        CompactSUV = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("SUV")]
        SUV = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("MiniBus")]
        MiniBus = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Van")]
        Van = 8,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Pickup")]
        Pickup = 9
    }
        /// <summary>
        /// There are no comments for EngineType in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EngineType")]
    public enum EngineType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Diesel")]
        Diesel = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Petrol")]
        Petrol = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hybrid_Electric_Diesel")]
        Hybrid_Electric_Diesel = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hybrid_Electric_Petrol")]
        Hybrid_Electric_Petrol = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Electric")]
        Electric = 4
    }
        /// <summary>
        /// There are no comments for TransmissionType in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TransmissionType")]
    public enum TransmissionType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Auto")]
        Auto = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Manual")]
        Manual = 1
    }
        /// <summary>
        /// There are no comments for PickupCargoAccessoryType in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PickupCargoAccessoryType")]
    public enum PickupCargoAccessoryType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("None")]
        None = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("TonneauCover")]
        TonneauCover = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("TruckCap")]
        TruckCap = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DomainModel.Entities.VehicleMake as global::DomainModel.Entities.VehicleMakeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::DomainModel.Entities.VehicleMakeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.VehicleMake> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::DomainModel.Entities.VehicleMakeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DomainModel.Entities.VehicleMake as global::DomainModel.Entities.VehicleMakeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="vehicleMakeId">The value of vehicleMakeId</param>
        public static global::DomainModel.Entities.VehicleMakeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.VehicleMake> _source,
            global::System.Guid vehicleMakeId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "VehicleMakeId", vehicleMakeId }
            };
            return new global::DomainModel.Entities.VehicleMakeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DomainModel.Entities.MotorVehicleModel as global::DomainModel.Entities.MotorVehicleModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::DomainModel.Entities.MotorVehicleModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicleModel> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::DomainModel.Entities.MotorVehicleModelSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DomainModel.Entities.MotorVehicleModel as global::DomainModel.Entities.MotorVehicleModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="motorVehicleModelId">The value of motorVehicleModelId</param>
        public static global::DomainModel.Entities.MotorVehicleModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicleModel> _source,
            global::System.Guid motorVehicleModelId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "MotorVehicleModelId", motorVehicleModelId }
            };
            return new global::DomainModel.Entities.MotorVehicleModelSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DomainModel.Entities.MotorVehicle as global::DomainModel.Entities.MotorVehicleSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::DomainModel.Entities.MotorVehicleSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicle> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::DomainModel.Entities.MotorVehicleSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DomainModel.Entities.MotorVehicle as global::DomainModel.Entities.MotorVehicleSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DomainModel.Entities.MotorVehicleSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicle> _source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DomainModel.Entities.MotorVehicleSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Default
{
        /// <summary>
        /// There are no comments for Container in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DomainModel.Entities", "DomainModel.Entities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("DomainModel.Entities", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DomainModel.Entities.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DomainModel.Entities.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for VehicleMakes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VehicleMakes")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.VehicleMake> VehicleMakes
        {
            get
            {
                if ((this._VehicleMakes == null))
                {
                    this._VehicleMakes = base.CreateQuery<global::DomainModel.Entities.VehicleMake>("VehicleMakes");
                }
                return this._VehicleMakes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.VehicleMake> _VehicleMakes;
        /// <summary>
        /// There are no comments for MotorVehicleModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicleModels")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicleModel> MotorVehicleModels
        {
            get
            {
                if ((this._MotorVehicleModels == null))
                {
                    this._MotorVehicleModels = base.CreateQuery<global::DomainModel.Entities.MotorVehicleModel>("MotorVehicleModels");
                }
                return this._MotorVehicleModels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicleModel> _MotorVehicleModels;
        /// <summary>
        /// There are no comments for MotorVehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MotorVehicles")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicle> MotorVehicles
        {
            get
            {
                if ((this._MotorVehicles == null))
                {
                    this._MotorVehicles = base.CreateQuery<global::DomainModel.Entities.MotorVehicle>("MotorVehicles");
                }
                return this._MotorVehicles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DomainModel.Entities.MotorVehicle> _MotorVehicles;
        /// <summary>
        /// There are no comments for VehicleMakes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToVehicleMakes(global::DomainModel.Entities.VehicleMake vehicleMake)
        {
            base.AddObject("VehicleMakes", vehicleMake);
        }
        /// <summary>
        /// There are no comments for MotorVehicleModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMotorVehicleModels(global::DomainModel.Entities.MotorVehicleModel motorVehicleModel)
        {
            base.AddObject("MotorVehicleModels", motorVehicleModel);
        }
        /// <summary>
        /// There are no comments for MotorVehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMotorVehicles(global::DomainModel.Entities.MotorVehicle motorVehicle)
        {
            base.AddObject("MotorVehicles", motorVehicle);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"VehicleRentalServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
